### ISSUE TITLE
dashman vote not working after update to 12.1

### ISSUE THREAD

**Issue by klenac1** [moocowmoo/dashman#14]
```
$ ~/dashman/dashman vote
dashman version 0.1.23 (1-g1601750) 
gathering info, please wait...  DONE!

Traceback (most recent call last):
  File "/home/mn/dashman/bin/dashvote.py", line 431, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/mn/dashman/bin/dashvote.py", line 225, in main
    ballots = json.loads(run_command('dash-cli mnbudget show'))
  File "/home/mn/dashman/bin/dashvote.py", line 64, in run_command
    return subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'dash-cli mnbudget show' returned non-zero exit status 89
Exiting.
```

**Comment by yellowcox** [comment]
Hi,
Exact same problem for me
Thx

**Comment by moocowmoo** [comment]
Unfortunately, the data I need to track has changed significantly enought
for this to be a non-trivial patch.

I recommend using dashcentral.org in the interim.  It may be a few weeks.

moocowmoo

**Comment by moocowmoo** [comment]
repaired in 16abd6c
